### PR TITLE
FIX: changed flaky search locator for messages

### PR DESCRIPTION
**Pull request by asanzgom**

### CODE REVIEW

**Review by Frawless — DISMISSED** [review]
We should understand the problem better instead of changing the locator which will probably not resolve the issue from my POV.

**Comment by rkubis** [comment]
> We should understand the problem better instead of changing the locator which will probably not resolve the issue from my POV.

I agree with @Frawless here, it looks that `Search` button is disabled when it should be enabled for searching.

This is very probably workaround for bug in UI.

**Comment by asanzgom** [comment]
ok, reviewing another approaches

**Comment by asanzgom** [comment]
There is a bug on UI reported here: https://issues.redhat.com/browse/MGDX-337

Should I adapt the test meanwhile @Frawless @rkubis @mmusil ?

**Comment by Frawless** [comment]
@asanzgom yes please, make sure that the test is working or is skipped until the issue will be resolved.

**Pull request merged**
