### PR TITLE
Fix: Messaging tests should wait for Instance to be ready

### PR DESCRIPTION
**Pull request by mmusil**

### CODE REVIEW

**Review by kornys — APPROVED** [review]

**Comment by asanzgom** [comment]
@mmusil Have you checked that all tests in this file need it?

**Review by asanzgom — APPROVED** [review]

**Comment by mmusil** [comment]
> @mmusil Have you checked that all tests in this file need it?

@asanzgom Yeah, all tests in this file need the instance to be ready.

**Comment by mmusil** [comment]
The stage did not load in one minute and the retry of the failed test passed from looking at the artefacts and reports. Should we ignore the PR build?

**Comment by asanzgom** [comment]
> The stage did not load in one minute and the retry of the failed test passed from looking at the artifacts and reports. Should we ignore the PR build?

No, retry the build

**Comment by mmusil** [comment]
> > The stage did not load in one minute and the retry of the failed test passed from looking at the artifacts and reports. Should we ignore the PR build?
> 
> No, retry the build

It is not related to the PR at all.

**Comment by kornys** [comment]
merge it if you want

**Pull request merged**
